FROM node:8.11.1

LABEL maintainer="bran@feedmob.com"

WORKDIR /app

ARG REACT_APP_API_URI
ARG REACT_APP_WS_URI
ARG REACT_APP_CLIENT_URL
ARG REACT_APP_SERVER_URL
ARG REDIS_URL
ARG REDIS_PORT
ARG REDIS_CACHE_PREFIX
ARG SENTRY_DSN_SERVER
ARG SENTRY_NAME
ARG DATABASE_NAME
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_PASSWORD
ARG SSR_PORT
ARG NODE_ENV
ARG SESSION_COOKIE_SECRET
ARG REACT_APP_MAINTENANCE_MODE

ENV REACT_APP_API_URI $REACT_APP_API_URI
ENV REACT_APP_WS_URI $REACT_APP_WS_URI
ENV REACT_APP_CLIENT_URL $REACT_APP_CLIENT_URL
ENV REACT_APP_SERVER_URL $REACT_APP_SERVER_URL
ENV REDIS_URL $REDIS_URL
ENV REDIS_PORT $REDIS_PORT
ENV REDIS_CACHE_PREFIX $REDIS_CACHE_PREFIX
ENV SENTRY_DSN_SERVER $SENTRY_DSN_SERVER
ENV SENTRY_NAME $SENTRY_NAME
ENV DATABASE_NAME $DATABASE_NAME
ENV DATABASE_HOST $DATABASE_HOST
ENV DATABASE_PORT $DATABASE_PORT
ENV DATABASE_PASSWORD $DATABASE_PASSWORD
ENV SSR_PORT $SSR_PORT
ENV NODE_ENV $NODE_ENV
ENV SESSION_COOKIE_SECRET $SESSION_COOKIE_SECRET
ENV REACT_APP_MAINTENANCE_MODE $REACT_APP_MAINTENANCE_MODE

# Only copy package.json and yarn.lock instead of all files
COPY package.json ./
COPY yarn.lock ./

# Do not install devDependencies
RUN yarn install
RUN yarn global add serve

# Bundle app source
COPY . .

RUN yarn run build && yarn run build:ssr

EXPOSE 5000
EXPOSE 3006

# Start the server
CMD [ "yarn", "run", "start:ssr" ]
