import React from 'react'
import Link from '../../components/link'
import { connect } from 'react-redux'
import slugg from 'slugg'
import { withApollo } from 'react-apollo'
import { Notice } from '../../../../components/listItems/style'
import Avatar from '../../../../components/avatar'
import { throttle } from '../../../../helpers/utils'
